package com.laytin.emailService.models;

public enum City {
    Minsk, Homyel, Vitsyebsk, Hrodna, Mahilyow, Brest, Babruysk, Baranavichy, Barysaw, Pinsk, Orsha,
    Navapolatsk, Salihorsk, Mazyr, Lida, Maladzyechna, Polatsk, Zhlobin, Rechytsa, Zhodzina, Svyetlahorsk, Slutsk,
    Kobryn, Slonim, Vawkavysk, Kalinkavichy, Smarhon, Rahachow, Horki, Asipovichy, Dzyarzhynsk, Byaroza, Navahrudak,
    Vilyeyka, Krychaw, Luninyets,Ivatsevichy, Mariina_Horka, Pastavy, Pruzhany, Dobrush, Hlybokaye, Zaslawye,Fanipal, Stowbtsy, Lyepyel, Shklow, Bykhaw, Ashmyany, Zhytkavichy, Smalyavichy, Ivanava,
    Kastsyukovichy, Shchuchyn, Lahoysk, Klimavichy, Masty, Drahichyn, Astravyets, Zhabinka,Nyasvizh,
    Hantsavichy,
    Khoyniki,
    Stolin,
    Malaryta,
    Mikashevichy,
    Novalukoml,
    Haradok,
    Lyuban,
    Klyetsk,
    Byerazino,
    Darohi,
    Byelaazyorsk,
    Lyakhavichy,
    Uzda,
    Chavusy,
    Baran,
    Kapyl,
    Mstsislaw,
    Skidal,
    Pyetrykaw,
    Byarozawka,
    Valozhyn,Byalynichy, Talachyn, Braslaw, Yelsk, Buda, Kashalyova, Chachersk, Krupki, Vyetka, Narowlya, Kamyanyets, Kirawsk, Chashniki, Dzyatlava, Slawharad, Cherykaw, Myory, Karma, Kruhlaye, Syanno, Iwye, Klichaw,
    Aktsyabrski,
    Hlusk,
    Myadzyel,
    Voranava,
    Vyerkhnyadzvinsk,
    Dokshytsy,
    Dubrowna,
    Loyew,
    Lyozna,
    Sharkawshchyna,
    Svislach,
    Khotsimsk,
    Davyd,
    Krasnapollye,
    Byerastavitsa,
    Chysts,
    Rasony,
    Vysokaye, Brahin, Vasilyevichy, Drybin, Turaw, Kosava, Dzisna, Nasilava, Andreyewshchyna, Lyelchytsy
}
